### ISSUE TITLE
Error deposit

### ISSUE THREAD

**Issue by Newyorkcoinholder** [tokenstore/apidocs#10]
Hi

Impossible to deposit nplay from personnaly wallet to exchange wallet. I tried 4 times changing gas price. " Warning error encountred during contract execution (reverted). No problem to transfert  eth from personnaly wallet to exchange wallet

**Comment by ghost** [comment]
@Newyorkcoinholder,
Is `nplay` ERC20 token? Does deposit work through UI on the site?

**Comment by Newyorkcoinholder** [comment]
Hi. Yes eplay and nplay are erc20 but now I see that they are delisted from token.store

**Comment by ghost** [comment]
Could you send transactions link from https://etherscan.io/ ?

**Comment by Newyorkcoinholder** [comment]
https://etherscan.io/tx/0x9f8b46b345ad871208b524da66a4faf70acad3412c2c0ee5e2e126457e2109e5 . I tried several times  and lost fees

**Comment by Newyorkcoinholder** [comment]
I tried with low , middle and high gas

**Comment by ghost** [comment]
Closed as not active.
